name: Tests
run-name: ${{ github.actor }} is running tests
on:
  - push

env:
  MIX_ENV: test

jobs:
  mix-test:  
    services:
      db:
        image: postgres:14.6-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gitsudo_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.2
          elixir-version: 1.14.3
      - run: mix deps.get
      - run: mix test
